title: "smf-to-ym2151log-rust"
description: "smf-to-ym2151log-rust"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/smf-to-ym2151log-rust
plugins:
  - jekyll-sitemap
